### PR TITLE
advanced cable plate placing

### PR DESCRIPTION
**Pull request by DS-Minetest**
raster
If you hold the use key / aux1 / turbo / E, you can place it into another direction.

### CODE REVIEW

**Comment by VanessaE** [comment]
Ordinarily, shift/sneak is used to initiate an alternate placement or whatever.  Might want to consider it.

**Comment by DS-Minetest** [comment]
Yes but if you fly you don't want to fly down while placing precisely. Also for what else would you need to press the aux1 button while placing a cable plate?
So, I think, aux1 makes more sense than sneak.

**Comment by VanessaE** [comment]
Well, for me, aux1 IS the fly-down key (an assignment I kept from before shift became the default).

**Comment by DS-Minetest** [comment]
I'll make both possible as compromise.

**Comment by DS-Minetest** [comment]
Now you have to hold one of them but not both.

**Comment by DS-Minetest** [comment]
I hope, this comment now doesn't extend the range of this PR.

**Comment by DS-Minetest** [comment]
Could someone please review this PR? It's lying here already for weeks ready to be merged.

**Pull request merged**
