### PR TITLE
Fix issue #474 by adding a crafting recipe for  technic:rubber without the grinder

### PR DESCRIPTION
**Pull request by TechDudie**

### CODE REVIEW

**Comment by SmallJoker** [comment]
Why? (general)

And why only for 0.4.x clients? `depends.txt` is ignored when `mod.conf` is found within the mod.

**Comment by TechDudie** [comment]
So issue #474 can be closed. When I first downloaded technic and the dependencies, I couldn’t make a few things. I went here and then realized I needed mesecons_materials. This is annoying for people who are new to technic.

**Comment by SmallJoker** [comment]
Technic is already quite dependency-heavy. If it's within your capabilities, I'd like it very much to have an alternative recipe for `technic:raw_latex 4` -> furnace cooking -> `technic:rubber 4` (or 2) if  `mesecons_materials` is not available.

**Comment by TechDudie** [comment]
Hmmmm..... maybe a new solution can be used instead of a new dependency.....

**Comment by TechDudie** [comment]
Perhaps you can craft 4 raw latex and 5 coal into 2 rubber things.....

**Comment by TechDudie** [comment]
It’s “collecting” the loose bits of coal that come off of the lumps.

**Comment by TechDudie** [comment]
Actually on second though, it crafts a rubber goo that can be smelted into rubber. I’ll add the changes now.

**Comment by TechDudie** [comment]
Ok, changes made.

**Comment by TechDudie** [comment]
Oops......

**Review by SmallJoker — APPROVED** [review]
LGTM. WIll merge in a few days if there are no objections.

**Comment by TechDudie** [comment]
Ok

**Pull request merged**
