### PR TITLE
Optimize PNG images losslessly

### PR DESCRIPTION
**Pull request by Calinou**
Commands used:

- `parallel optipng -o7 -zm1-9 -strip all ::: **/*.png`
- `parallel advpng -z4 ::: **/*.png`

This incorporates non-interlacted PNGs from #500 to fix warnings thrown by libpng.

### CODE REVIEW

**Comment by SmallJoker** [comment]
In fact I now get flooded with new warnings:
```
2019-06-18 21:08:27: WARNING[Main]: Irrlicht: PNG warning: bKGD: invalid index
2019-06-18 21:08:27: WARNING[Main]: Irrlicht: PNG warning: bKGD: invalid index
```

**Comment by Calinou** [comment]
I fixed almost all warnings by using a Git build of oxipng. However, I still get one of those bKGD warnings (it might be on a texture from a dependency, not sure) and a few interlace warnings:

```
2019-06-18 23:53:59: WARNING[Main]: Irrlicht: PNG warning: bKGD: invalid index
2019-06-18 23:53:59: WARNING[Main]: Irrlicht: PNG warning: Interlace handling should be turned on when using png_read_image
2019-06-18 23:53:59: WARNING[Main]: Irrlicht: PNG warning: Interlace handling should be turned on when using png_read_image
2019-06-18 23:53:59: WARNING[Main]: Irrlicht: PNG warning: Interlace handling should be turned on when using png_read_image
```

**Comment by SmallJoker** [comment]
Those warnings should be solved too. From verbose: (stripped timestamps)
```
VERBOSE[Main]: Client: Attempting to load image file "technic_chromium_lump.png"
WARNING[Main]: Irrlicht: PNG warning: bKGD: invalid index

VERBOSE[Main]: Client: Attempting to load image file "technic_hydro_turbine_side.png"
WARNING[Main]: Irrlicht: PNG warning: Interlace handling should be turned on when using png_read_image

VERBOSE[Main]: Client: Attempting to load image file "technic_hydro_turbine_top.png"
WARNING[Main]: Irrlicht: PNG warning: Interlace handling should be turned on when using png_read_image

VERBOSE[Main]: Client: Attempting to load image file "technic_hydro_turbine_top_active.png"
WARNING[Main]: Irrlicht: PNG warning: Interlace handling should be turned on when using png_read_image
```

**Comment by Calinou** [comment]
I remade this pull request by using OptiPNG + advpng instead of oxipng. It seems to work without warnings now :slightly_smiling_face:

**Pull request merged**
