### PR TITLE
use clear_craft

### PR DESCRIPTION
**Pull request by DS-Minetest**
related: #292

### CODE REVIEW

**Comment by Thomas--S** [comment]
I highly doubt that this works as expected.

According to [`lua_api.txt`](https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L2045), you can specify either output or input only.

**Comment by DS-Minetest** [comment]
Oh, you are right, so now input is ignored. Shall input or output be cleared?

**Comment by Thomas--S** [comment]
I think that depends on two things:

- Are the recipes cleared before the new ones are registered?
- Do we want to
   - disable one specific recipe? => clear input
   - disable all recipes except the ones that the technic mod defines for a certain item? => clear output

**Comment by DS-Minetest** [comment]
Yep, we want to clear it before registering the others, so I moved up. Also we want to clear the outputs, so that the technic recipes are the only valid ones. (So, the moreores tin-copper recipe for bronze is also cleared now, I think, that's good.)

**Pull request merged**
