### PR TITLE
Add LV lights

### PR DESCRIPTION
**Pull request by blockhead100**
New lights like technic + and some new textures for hv tools!!

### CODE REVIEW

**Comment by blockhead100** [comment]
i removed the HV tools but left the textures.

**Comment by blockhead100** [comment]
i messed up readme and modpack.conf, so i fixed those.

**Comment by blockhead100** [comment]
For my server i wanted the quarry to go deeper, i made that change and forgot to change it back.

**Comment by SmallJoker** [comment]
:-1: 

 - The small LEDs do not look good; it should cover the cable entirely at least on one side
 - Either the LED or LV lamp have wrong sunlight_propagates/paramtype values. Placing them next to each other results in weird shadows
 - LV lamps could be a lot thinner for the small light they can actually produce

Generally it might be interesting to use  moreblocks' glow light or lamp to power. The white ones look quite nice and do cover up the cables (for example on the ceiling).

**Comment by blockhead100** [comment]
Ok... so you think a the textures and the sunlight_propagates/paramtype values should be changed?

**Comment by blockhead100** [comment]
I am working on the textures.

**Comment by SmallJoker** [comment]
Sorry, I did not notice that you were done. Feel free to @ me when I ever forget things.

I could not apply the patch, thus squashed & rebased the branch. Now it appears that GitHub lost track of it, hence I uploaded it to https://github.com/minetest-mods/technic/tree/lv_lights to continue development on my own :confused: .

**Comment by SmallJoker** [comment]
Merged.

**Comment by blockhead100** [comment]
Ok thanks so much!!

**Pull request closed without merging**
