### PR TITLE
Changing recipe proportions

### PR DESCRIPTION
**Pull request by BobFred7**
I changed the proportions of ingredients in alloy furnace recipes to make technic more realistic (issue #516):
Carbon steel: 1 wrought iron + 1 coal -> 2 wrought iron + 1 coal
Cast iron: 1 carbon steel + 1 coal -> 2 carbon steel + 1 coal
Stainless steel: 3 carbon steel + 1 chromium -> 4 carbon steel + 1 chromium
Bronze: 3 copper + 1 tin -> 7 copper + 1 tin
I also changed the output quantities to match these changes.
All changes are in technic/machines/register/alloy_recipes.lua

### CODE REVIEW

**Comment by Ekdohibs** [comment]
This seems good. However, to keep the balance, I think it would be better to increase the time of the various recipes, as you increased the number of items they handle at the same time.

**Comment by BobFred7** [comment]
I also intend to somehow blacklist the cast iron recipe from cooking in electric furnaces

**Comment by BobFred7** [comment]
Clarification: The blacklisting will be done separately. This PR is complete except for the merging (as far as I can tell).

**Comment by BobFred7** [comment]
Uh, it's been almost a month
Is there a problem with this? Is it going to get merged?

**Comment by SmallJoker** [comment]
@BobFred7 Currently there are no changes to merge. Please avoid pull requests using your master branch.

**Comment by BobFred7** [comment]
Right, whoops, I'll redo the alloy recipe changes in another branch and try to merge that.

**Comment by SmallJoker** [comment]
#549

**Pull request closed without merging**
