### PR TITLE
fix #463 optimize variable access

### LINKED ISSUE #463: Important oregen memory use optimisation
My earlier advice in https://forum.minetest.net/viewtopic.php?f=18&t=16043&p=324628#p324628 still had some misunderstandings, has now been updated.
The further change needed is point 3 in the forum thread and is simple:
https://github.com/minetest-mods/technic/blob/bdd13beeff5045a34042439e39620b9ca550b214/technic_worldgen/oregen.lua#L149
Change to:
`local data = {}`
https://github.com/minetest-mods/technic/blob/bdd13beeff5045a34042439e39620b9ca550b214/technic_worldgen/oregen.lua#L155
Change to:
`vm:get_data(data)`

This will greatly reduce Lua memory use and reduce chance of OOM when using LuaJIT.

### PR DESCRIPTION
**Pull request by thomasrudin**
fix #463 optimize variable access

### CODE REVIEW

**Comment by SmallJoker** [comment]
This will permanently keep some memory allocated of the last generated map chunk. The data was duplicated, so I suggest to drop the variable `sulfur_buf` in favour of a temporary local variable.
-> `local data = vm:get_data()`

**Comment by thomasrudin** [comment]
I don't think thats an issue, see point 3 here: https://forum.minetest.net/viewtopic.php?f=18&t=16043&p=324628#p242631

**Comment by paramat** [comment]
Just seen this, will review.

**Comment by paramat** [comment]
SmallJoker, using `get_data([buffer])` was specifically added by hmmmm to optimise memory use.
However it's possible my memory optimisation advice is wrong in some way.

**Comment by paramat** [comment]
It would be easier to just use 'data' as the buffer, as suggested in the issue, less chance of mistakes.

**Comment by paramat** [comment]
> This will permanently keep some memory allocated of the last generated map chunk.

Seems so, but that's not nearly as bad as not having the opimisation, and i assume this memory will be cleared when exiting to menu?

**Comment by SmallJoker** [comment]
I'm not sure how I got the idea of my previous comment. Maybe I forgot about the garbage collector delay and was confused by the C++ source code.
https://github.com/minetest/minetest/blob/f5bdc04ab5b47bd094ba0ced5f086e8fe6b12298/src/script/lua_api/l_vmanip.cpp#L61-L84
In fact the sulfur code is already optimized. In `get_data` `sulfur_buf` is taken for the loop to re-write its contents. `data` is then set to the _(table) reference_  of `sulfur_buf`, thus no copying is involved here. So in this PR you're kinda only removing a local table reference (a few bytes).

**Comment by paramat** [comment]
Hmm maybe my memory optimisation advice is wrong in this aspect then.

**Comment by paramat** [comment]
PR needs improving:
> It would be easier and clearer to just use 'data' as the buffer, as suggested in the issue. The code is already using 'data' for the voxelmanip array (as is common practice) so best to continue that, it's more important than preserving the variable name 'sulfur_buf'.

**Comment by thomasrudin** [comment]
Enough bikeshedding

**Pull request closed without merging**
